### ISSUE TITLE
Helper functions

### ISSUE THREAD

**Issue by palpatel0** [lisds/project-daylight-robbery#11]
functions to add together/merge columns across offences by the month/for the year/total, but still separated by borough.

**Comment by TomWFox** [comment]
I think the addition of `MultiIndex` solves this - it makes these kinds of operations fairly trivial with pandas

**Comment by TomWFox** [comment]
Yes...
![CleanShot 2023-12-11 at 12 36 05@2x](https://github.com/lisds/project-daylight-robbery/assets/13188249/259fa8bb-33e6-45b0-8e67-9ca8efddbd68)
