### ISSUE TITLE
Progress checkin

### ISSUE THREAD

**Issue by matthew-brett** [lisds/project-daylight-robbery#16]
As promised (on Friday) - here's your issue asking for a progress checkin.

Could you reply to this issue post with a brief bullet-point summary of a couple paragraphs, letting me know where you are?    A really useful summary will:

* Summarize your data
* Describe your initial analysis strategy
* What you have tried so far.
* What worked and what did not.
* What you plan to do next.

**Comment by TomWFox** [comment]
Sorry we didn't get round to responding Matthew :/ Hopefully our presentation was a good update
