### ISSUE TITLE
Initial exploration

### ISSUE THREAD

**Issue by TomWFox** [lisds/project-daylight-robbery#4]
We can use this issue to share ideas of how we can explore the data and any resulting insights. This will help to inform the future direction of the project.

Please share what you're learning even if it isn't ready to be a PR yet - this will help us move faster as a team and make sure we're not wasting time looking into the same stuff.

What I suggested we could look into:

> I think it could be interesting to compare general trends in different crimes across boroughs, maybe investigate recent crimes relating to Just Stop Oil and Israel-Palestine related activity. As Pal suggested, it could be interesting to investigate if there are any interesting time-of-year / daylight saving time trends. Although this could be implausible due to only having aggregate crimes by month rather than time / date of individual crimes.
>
> The Met also provide a 'use of force' dataset (only has borough geographical data) - it could be interesting to see what can be learned from bringing the two together. Maybe to see if changes in numbers of particular crimes correlate with change in use of force – thus potentially allowing attribution of particular crimes to a disproportionate volume of use of force.
>
> Due to limitations in the fidelity of the crime summary dataset it may be that we end up focusing in more on the use of force data.
>
>Use of force: https://data.london.gov.uk/dataset/use-of-force, data runs from 2017 – Oct 2023
>
> Finally there is also LSOA and ward level 2021 census info on the London Datastore (e.g. labour market, religion, migration, demographic etc). Combining ward or LSOA census data and the crime data could be cool.
>
> Census data: https://data.london.gov.uk/dataset?org=be83dfcf-79d3-4a6e-aa28-df33dc6bc3d8&page=1

**Comment by palpatel0** [comment]
[police-funding-england-and-wales-2015-to-2023-tables.ods](https://github.com/lisds/project-daylight-robbery/files/13637293/police-funding-england-and-wales-2015-to-2023-tables.ods)
[regionalincomeandproductivitydata.xlsx](https://github.com/lisds/project-daylight-robbery/files/13637294/regionalincomeandproductivitydata.xlsx)
[earnings-residence-borough.xlsx](https://github.com/lisds/project-daylight-robbery/files/13637296/earnings-residence-borough.xlsx)

**Comment by palpatel0** [comment]
https://github.com/lisds/project-daylight-robbery/issues/13#issue-2024849956
Accidentally started my own issue because I didn't see this

**Comment by palpatel0** [comment]
Could get data about affluence for borough and compare the prevalence of different types of crime.
Could get data about met police funding over the years and see the correlation with crimes. Not causation of course but could be that there are less arrests/convictions because less police

**Comment by palpatel0** [comment]
> We can use this issue to share ideas of how we can explore the data and any resulting insights. This will help to inform the future direction of the project.
> 
> Please share what you're learning even if it isn't ready to be a PR yet - this will help us move faster as a team and make sure we're not wasting time looking into the same stuff.
> 
> What I suggested we could look into:
> 
> > I think it could be interesting to compare general trends in different crimes across boroughs, maybe investigate recent crimes relating to Just Stop Oil and Israel-Palestine related activity. As Pal suggested, it could be interesting to investigate if there are any interesting time-of-year / daylight saving time trends. Although this could be implausible due to only having aggregate crimes by month rather than time / date of individual crimes.
> > The Met also provide a 'use of force' dataset (only has borough geographical data) - it could be interesting to see what can be learned from bringing the two together. Maybe to see if changes in numbers of particular crimes correlate with change in use of force – thus potentially allowing attribution of particular crimes to a disproportionate volume of use of force.
> > Due to limitations in the fidelity of the crime summary dataset it may be that we end up focusing in more on the use of force data.
> > Use of force: https://data.london.gov.uk/dataset/use-of-force, data runs from 2017 – Oct 2023
> > Finally there is also LSOA and ward level 2021 census info on the London Datastore (e.g. labour market, religion, migration, demographic etc). Combining ward or LSOA census data and the crime data could be cool.
> > Census data: https://data.london.gov.uk/dataset?org=be83dfcf-79d3-4a6e-aa28-df33dc6bc3d8&page=1

One of the issues with using census data is that it has two data points (2011 and 2021). It would be more fruitful to compare data that is over the same number of years, perhaps, so it's easier to see a trend?

**Comment by TomWFox** [comment]
yes that is fair, I think where it is helpful is in the geographical fidelity. both the census and the data might be helpful for anyone who wants to do funky stuff

**Comment by TomWFox** [comment]
https://data.london.gov.uk/dataset/ward-profiles-and-atlas

Just to highlight... profiles here about every ward - pretty cool
